// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.grpc;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 2;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
